### ISSUE TITLE
Make sidebar configurable

### ISSUE THREAD

**Issue by fno2010** [snlab-freedom/hugo-theme-cooler#2]
Currently, the sidebar of the site is hard coded in the theme layout. Check the files `layout/partials/widgets/download.html` and `layout/partials/widgets/documentation.html`.

We need to do the following changes at least:

- [x] Download widgets may not be necessary for us. The naive solution is to remove this button. But we can think about another useful widget to replace it.
- [x] Documentation widget should be very helpful. But we don't want to hard code its content in the theme. Move the content to `config.toml`.

Further more, we can make the sidebar totally configurable. For example, each widget can be configured to be displayed or not.

**Comment by yjlcoder** [comment]
Done.
